# Generated by Django 3.2.25 on 2025-01-13 04:00

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20250113_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=recipes.models.recipe_image_file_path),
        ),
    ]
